---
title: "3 advanced {disk.frame}"
author: "ZJ"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Basics 





## Ingesting data




Let's "generate" a dataset for {disk.frame}

Let `n=4`. You can increase `n` if you are game!

We will append the nyc::flights dataset together 4 times.

* generate a fake dataset that is reasonably large (so avoiding a large download from internet)
* Convert the dataset to CSV
* Show how to load the data from CSV to {disk.frame}
* Manipulate the {disk.frame}
* Do group-by and summary statistics with {disk.frame}
* show how dplyr and data.table syntax can operate on {disk.frame}
* Explain how to perform group-by efficiently 
* Demonstrate how joining works for large {disk.frame}s

**** break ****

After the break, we will cover advanced {disk.frame} topics

* Explain how to extend {disk.frame} with a custom function
* Explain how to tune {disk.frame} for maximum efficiency
* Show some convenience features for {disk.frame} in RStudio if time permits
* Conclusion and Q&A